$env:AHOOTSA_VERSION = '5.0.42'
$env:AHOOTSA_LOG_ROOT = 'D:\RITXI\logs'
$env:AHOOTSA_CAMERA_DIR = 'D:\RITXI\logs\camera'
$env:AHOOTSA_LLM_PROVIDER = 'ollama'
$env:AHOOTSA_OLLAMA_MODEL = 'llama3.2:3b'
$env:AHOOTSA_OLLAMA_BASE_URL = 'http://127.0.0.1:11434'
$env:AHOOTSA_OLLAMA_TIMEOUT = '25'
$env:AHOOTSA_HF_MODEL_PATH = ''
$env:AHOOTSA_VOICE = 'Sohee'
Add-Content -Encoding UTF8 -LiteralPath 'D:\RITXI\logs\ahootsa5_20260708_231956_runtime.log' -Value ('START_DAEMON ' + (Get-Date -Format o))
& 'C:\Users\Alumno\AppData\Local\Reachy Mini Control\apps_venv\Scripts\reachy-mini-daemon.exe' --sim --fastapi-host 127.0.0.1 --fastapi-port 8000 --no-goto-sleep-on-stop --dataset-update-interval 0 --no-preload-datasets --log-file 'D:\RITXI\logs\ahootsa5_20260708_231956_runtime.log'
