$env:AHOOTSA_VERSION='5.0.43'
$env:AHOOTSA_LOG_ROOT='D:\RITXI\logs'
$env:AHOOTSA_CAMERA_DIR='D:\RITXI\logs\camera'
$env:AHOOTSA_LLM_PROVIDER='ollama'
$env:AHOOTSA_OLLAMA_MODEL='llama3.2:3b'
$env:AHOOTSA_OLLAMA_BASE_URL='http://127.0.0.1:11434'
$env:AHOOTSA_OLLAMA_TIMEOUT='25'
$env:AHOOTSA_VOICE='Sohee'
$env:VOICE='Sohee'
$env:REACHY_MINI_VOICE='Sohee'
$env:OPENAI_REALTIME_VOICE='Sohee'
$env:REALTIME_VOICE='Sohee'
$env:TTS_VOICE='Sohee'
$env:AUDIO_VOICE='Sohee'
if ('' -ne '') { $env:AHOOTSA_HF_MODEL_PATH='' }
' START_DAEMON ' + (Get-Date -Format o) | Add-Content -LiteralPath 'D:\RITXI\logs\ahootsa5_20260708_233647_runtime.log'
& 'C:\Users\Alumno\AppData\Local\Reachy Mini Control\apps_venv\Scripts\reachy-mini-daemon.exe' --sim --fastapi-host 127.0.0.1 --fastapi-port 8000 --no-goto-sleep-on-stop --dataset-update-interval 0 --no-preload-datasets --log-file 'D:\RITXI\logs\ahootsa5_20260708_233647_runtime.log'
